- name: set the Message Of The Day (MOTD)
  become: true
  template:
    src: motd
    dest: "/etc/motd"
    mode: 0644

- name: "Print motd always"
  # Note that this is added at the end of the file, so 
  # with the default bashrc by Ubuntu, it's run only interactively
  # moreover, login shells already print it by default
  lineinfile: 
    path: "${HOME}/.bashrc"
    line: "shopt -q login_shell || cat /etc/motd # Print only in non-login shells"
