---
# Note: This is applied immediately, no restart needed
- name: set wallpaper
  dconf:
    key: /org/gnome/desktop/background/picture-uri
    value: "'file://{{ qm_customizations_custom_folder }}/quantum-mobile-bg.png'"
    state: present
