---
- name: restart gdm3
  become: true
  become_user: "{{ root_user }}"
  service:
    name: gdm3
    state: restarted
  listen: restart gdm
- name: restart gdm
  become: true
  become_user: "{{ root_user }}"
  service:
    name: gdm
    state: restarted
  listen: restart gdm3 

- name: restart lightdm
  become: true
  become_user: "{{ root_user }}"
  service:
    name: lightdm
    state: restarted
