---
- name: restart gdm3
  become: true
  become_user: "{{ root_user }}"
  service:
    name: gdm3
    state: restarted
- name: restart lightdm
  become: true
  become_user: "{{ root_user }}"
  service:
    name: lightdm
    state: restarted
